workflows:
  ios_release:
    name: iOS Release
    max_build_duration: 60

    environment:
      flutter: 3.29.3
      xcode: latest
      cocoapods: default

      # iOS code signing must live under environment › ios_signing
      ios_signing:
        # auto-fetch the App Store distribution cert + profile for this bundle
        distribution_type: app_store
        bundle_identifier: com.example.liftLeague

    triggering:
      events:
        - push
      # branch_patterns is a simple list of strings, not dicts :contentReference[oaicite:1]{index=1}
      branch_patterns:
        - pattern: "main"

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Print environment info
        script: |
          flutter --version
          pod --version
          xcodebuild -version
          env

      - name: Set build version
        script: |
          VERSION_LINE=$(grep '^version: ' pubspec.yaml | awk '{print $2}')
          BUILD_NAME=${VERSION_LINE%%+*}
          BUILD_NUMBER=${VERSION_LINE##*+}
          echo "BUILD_NAME=$BUILD_NAME" >> $CM_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      - name: Build IPA
        script: |
          flutter clean
          flutter build ipa \
            --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=ios/ExportOptions.plist\
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        api_key: CodemagicKey
        key_id: 6J6HAU4482
        issuer_id: 8FP674AG7R
        submit_to_testflight: true
        submit_to_app_store: false
