workflows:
  ios_release:
    name: iOS Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      # ✅ MOVE CODE SIGNING HERE:
      vars:
        APP_ID: "com.example.lift_league" # <-- Replace with your actual bundle ID

      # ✅ Code signing now goes inside environment:
      ios_signing:
        certificates:
          - goodhurt_key # <-- This is the name of your uploaded .p12 file
        provisioning_profiles: auto

    triggering:
      events:
        - push

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Set build version
        script: |
          VERSION_LINE=$(grep '^version: ' pubspec.yaml | awk '{print $2}')
          BUILD_NAME=$(echo $VERSION_LINE | cut -d "+" -f 1)
          BUILD_NUMBER=$(echo $VERSION_LINE | cut -d "+" -f 2)
          echo "BUILD_NAME=$BUILD_NAME" >> $CM_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      - name: Flutter clean & build iOS
        script: |
          flutter clean
          flutter build ios --release --no-codesign \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        api_key: goodhurt_key # This must also be defined under your App Store Connect API keys
        submit_to_testflight: true
        submit_to_app_store: false
        export_options: ios/ExportOptions.plist
