workflows:
  ios_release_with_shorebird:
    name: iOS Release with Shorebird
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        certificates:
          - goodhurt_key


      vars:
        APP_ID: "com.example.liftLeague"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Shorebird auth
        script: |
          dart pub global activate shorebird_cli
          shorebird login --token $SHOREBIRD_AUTH_TOKEN

      - name: Set build version
        script: |
          VERSION_LINE=$(grep '^version: ' pubspec.yaml | awk '{print $2}')
          BUILD_NAME=$(echo $VERSION_LINE | cut -d "+" -f 1)
          BUILD_NUMBER=$(echo $VERSION_LINE | cut -d "+" -f 2)
          echo "BUILD_NAME=$BUILD_NAME" >> $CM_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      - name: Build iOS with Shorebird
        script: |
          flutter clean
          shorebird flutter build ios --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        api_key: goodhurt_key
        key_id: WWR5JQ5K5X
        issuer_id: 85ac48ea-7393-4080-a8b2-58c9a95835d0
        submit_to_testflight: true
        submit_to_app_store: false