workflows:
  ios_release_with_shorebird:
    name: iOS Release with Shorebird
    max_build_duration: 60

    environment:
      flutter: 3.29.3
      xcode: latest
      cocoapods: default

      # iOS code signing must live under environment › ios_signing
      ios_signing:
        # auto-fetch the App Store distribution cert + profile for this bundle
        distribution_type: app_store
        bundle_identifier: com.example.liftLeague :contentReference[oaicite:0]{index=0}

    triggering:
      events:
        - push
      # branch_patterns is a simple list of strings, not dicts :contentReference[oaicite:1]{index=1}
      branch_patterns:
        - main

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Shorebird auth
        script: |
          dart pub global activate shorebird_cli
          shorebird login --token $SHOREBIRD_AUTH_TOKEN

      - name: Set build version
        script: |
          VERSION_LINE=$(grep '^version: ' pubspec.yaml | awk '{print $2}')
          BUILD_NAME=${VERSION_LINE%%+*}
          BUILD_NUMBER=${VERSION_LINE##*+}
          echo "BUILD_NAME=$BUILD_NAME" >> $CM_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      - name: Build IPA
        script: |
          flutter clean
          flutter build ipa \
            --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      # Use shorebird_release (not “shorebird”) when in codemagic.yaml :contentReference[oaicite:2]{index=2}
      shorebird_release:
        app_id: $APP_ID
        flutter_version: 3.29.3
        release_version: $BUILD_NAME
        build_number: $BUILD_NUMBER

      app_store_connect:
        api_key: goodhurt_key
        key_id: WWR5JQ5K5X
        issuer_id: 85ac48ea-7393-4080-a8b2-58c9a95835d0
        submit_to_testflight: true
        submit_to_app_store: false
