// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-S9E0p0mqCN_Y8loEyUAud-ygO8tTQY',
    appId: '1:997251967762:web:221ca302032bd7e26261cb',
    messagingSenderId: '997251967762',
    projectId: 'the-lift-league',
    authDomain: 'the-lift-league.firebaseapp.com',
    storageBucket: 'the-lift-league.appspot.com',
    measurementId: 'G-HSTE5R7S9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Gg33we_52xK0h9WvcR3GrFmsf04yLY4',
    appId: '1:997251967762:android:63878d02e1eac5a26261cb',
    messagingSenderId: '997251967762',
    projectId: 'the-lift-league',
    storageBucket: 'the-lift-league.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LMBDViiy8Kp4UTB9an-Uq3NNx7I8ftQ',
    appId: '1:997251967762:ios:9c93350c3aa2fd7f6261cb',
    messagingSenderId: '997251967762',
    projectId: 'the-lift-league',
    storageBucket: 'the-lift-league.appspot.com',
    iosBundleId: 'com.example.liftLeague',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1LMBDViiy8Kp4UTB9an-Uq3NNx7I8ftQ',
    appId: '1:997251967762:ios:9c93350c3aa2fd7f6261cb',
    messagingSenderId: '997251967762',
    projectId: 'the-lift-league',
    storageBucket: 'the-lift-league.appspot.com',
    iosBundleId: 'com.example.liftLeague',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_a9lzQZu0RPpEaTfJlQKSJMhHnuMtl68',
    appId: '1:997251967762:web:a2e4c462e2ad7e7b6261cb',
    messagingSenderId: '997251967762',
    projectId: 'the-lift-league',
    authDomain: 'the-lift-league.firebaseapp.com',
    storageBucket: 'the-lift-league.appspot.com',
    measurementId: 'G-D22L0EG6XE',
  );
}
