platform :ios, '15.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

require File.expand_path(
  File.join('packages', 'flutter_tools', 'bin', 'podhelper'),
  __dir__
)

flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
