platform :ios, '15.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require ENV['FLUTTER_ROOT'] + '/packages/flutter_tools/bin/podhelper.rb'

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
